### ISSUE TITLE
Unable to install 0.1.0 with Nim 0.18.0 using Nimble

### ISSUE THREAD

**Issue by zedeus** [juancarlospaco/nim-tinyslation#1]
It seems you forgot to bump the version number after fixing the requirement in this commit 17d02563fdee9d746b92c2755283bce04ba6739c, causing nimble to use an older version.

**Comment by juancarlospaco** [comment]
@zestyr It should be working now :grey_exclamation: :smile_cat:

**Comment by zedeus** [comment]
Thanks!
